// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: analytics/analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AnalyticsService_GetDashboardStats_FullMethodName            = "/analytics.AnalyticsService/GetDashboardStats"
	AnalyticsService_GetSalesChart_FullMethodName                = "/analytics.AnalyticsService/GetSalesChart"
	AnalyticsService_GetStatusDistribution_FullMethodName        = "/analytics.AnalyticsService/GetStatusDistribution"
	AnalyticsService_GetOperationTypeDistribution_FullMethodName = "/analytics.AnalyticsService/GetOperationTypeDistribution"
	AnalyticsService_GetTopContractors_FullMethodName            = "/analytics.AnalyticsService/GetTopContractors"
	AnalyticsService_GetMonthlyRevenue_FullMethodName            = "/analytics.AnalyticsService/GetMonthlyRevenue"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	// GetDashboardStats возвращает статистику для дашборда
	GetDashboardStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// GetSalesChart возвращает данные для графика продаж
	GetSalesChart(ctx context.Context, in *SalesChartRequest, opts ...grpc.CallOption) (*SalesChartResponse, error)
	// GetStatusDistribution возвращает распределение по статусам
	GetStatusDistribution(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// GetOperationTypeDistribution возвращает распределение по типам операций
	GetOperationTypeDistribution(ctx context.Context, in *OperationTypeRequest, opts ...grpc.CallOption) (*OperationTypeResponse, error)
	// GetTopContractors возвращает топ контрагентов
	GetTopContractors(ctx context.Context, in *TopContractorsRequest, opts ...grpc.CallOption) (*TopContractorsResponse, error)
	// GetMonthlyRevenue возвращает месячную выручку
	GetMonthlyRevenue(ctx context.Context, in *MonthlyRevenueRequest, opts ...grpc.CallOption) (*MonthlyRevenueResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetDashboardStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDashboardStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetSalesChart(ctx context.Context, in *SalesChartRequest, opts ...grpc.CallOption) (*SalesChartResponse, error) {
	out := new(SalesChartResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetSalesChart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetStatusDistribution(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetStatusDistribution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetOperationTypeDistribution(ctx context.Context, in *OperationTypeRequest, opts ...grpc.CallOption) (*OperationTypeResponse, error) {
	out := new(OperationTypeResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOperationTypeDistribution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopContractors(ctx context.Context, in *TopContractorsRequest, opts ...grpc.CallOption) (*TopContractorsResponse, error) {
	out := new(TopContractorsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopContractors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMonthlyRevenue(ctx context.Context, in *MonthlyRevenueRequest, opts ...grpc.CallOption) (*MonthlyRevenueResponse, error) {
	out := new(MonthlyRevenueResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMonthlyRevenue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility
type AnalyticsServiceServer interface {
	// GetDashboardStats возвращает статистику для дашборда
	GetDashboardStats(context.Context, *StatsRequest) (*StatsResponse, error)
	// GetSalesChart возвращает данные для графика продаж
	GetSalesChart(context.Context, *SalesChartRequest) (*SalesChartResponse, error)
	// GetStatusDistribution возвращает распределение по статусам
	GetStatusDistribution(context.Context, *StatusRequest) (*StatusResponse, error)
	// GetOperationTypeDistribution возвращает распределение по типам операций
	GetOperationTypeDistribution(context.Context, *OperationTypeRequest) (*OperationTypeResponse, error)
	// GetTopContractors возвращает топ контрагентов
	GetTopContractors(context.Context, *TopContractorsRequest) (*TopContractorsResponse, error)
	// GetMonthlyRevenue возвращает месячную выручку
	GetMonthlyRevenue(context.Context, *MonthlyRevenueRequest) (*MonthlyRevenueResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (UnimplementedAnalyticsServiceServer) GetDashboardStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetSalesChart(context.Context, *SalesChartRequest) (*SalesChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalesChart not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetStatusDistribution(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatusDistribution not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetOperationTypeDistribution(context.Context, *OperationTypeRequest) (*OperationTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperationTypeDistribution not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopContractors(context.Context, *TopContractorsRequest) (*TopContractorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopContractors not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMonthlyRevenue(context.Context, *MonthlyRevenueRequest) (*MonthlyRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyRevenue not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDashboardStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetSalesChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SalesChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetSalesChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetSalesChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetSalesChart(ctx, req.(*SalesChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetStatusDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetStatusDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetStatusDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetStatusDistribution(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetOperationTypeDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOperationTypeDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOperationTypeDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetOperationTypeDistribution(ctx, req.(*OperationTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopContractors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopContractorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopContractors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopContractors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopContractors(ctx, req.(*TopContractorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMonthlyRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthlyRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMonthlyRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMonthlyRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMonthlyRevenue(ctx, req.(*MonthlyRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardStats",
			Handler:    _AnalyticsService_GetDashboardStats_Handler,
		},
		{
			MethodName: "GetSalesChart",
			Handler:    _AnalyticsService_GetSalesChart_Handler,
		},
		{
			MethodName: "GetStatusDistribution",
			Handler:    _AnalyticsService_GetStatusDistribution_Handler,
		},
		{
			MethodName: "GetOperationTypeDistribution",
			Handler:    _AnalyticsService_GetOperationTypeDistribution_Handler,
		},
		{
			MethodName: "GetTopContractors",
			Handler:    _AnalyticsService_GetTopContractors_Handler,
		},
		{
			MethodName: "GetMonthlyRevenue",
			Handler:    _AnalyticsService_GetMonthlyRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/analytics.proto",
}
