// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: legacy/document_service.proto

package document

import (
	context "context"
	common "github.com/rusgainew/kkm-project-mks/proto-lib/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DocumentService_GetDocument_FullMethodName         = "/api.document.DocumentService/GetDocument"
	DocumentService_CreateDocument_FullMethodName      = "/api.document.DocumentService/CreateDocument"
	DocumentService_UpdateDocument_FullMethodName      = "/api.document.DocumentService/UpdateDocument"
	DocumentService_SendDocument_FullMethodName        = "/api.document.DocumentService/SendDocument"
	DocumentService_ApproveDocument_FullMethodName     = "/api.document.DocumentService/ApproveDocument"
	DocumentService_RejectDocument_FullMethodName      = "/api.document.DocumentService/RejectDocument"
	DocumentService_ArchiveDocument_FullMethodName     = "/api.document.DocumentService/ArchiveDocument"
	DocumentService_ListDocuments_FullMethodName       = "/api.document.DocumentService/ListDocuments"
	DocumentService_AddDocumentEntry_FullMethodName    = "/api.document.DocumentService/AddDocumentEntry"
	DocumentService_UpdateDocumentEntry_FullMethodName = "/api.document.DocumentService/UpdateDocumentEntry"
	DocumentService_RemoveDocumentEntry_FullMethodName = "/api.document.DocumentService/RemoveDocumentEntry"
	DocumentService_GetDocumentHistory_FullMethodName  = "/api.document.DocumentService/GetDocumentHistory"
)

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentServiceClient interface {
	// *
	// Получение документа по ID.
	// Запрос: document_id
	// Ответ: документ со всеми записями
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// *
	// Создание нового документа.
	// Запрос: organization_id, title, content, created_by
	// Ответ: document
	// Генерирует событие: DocumentCreatedEvent (через RabbitMQ)
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// *
	// Обновление документа.
	// Запрос: id, title, content
	// Ответ: document
	// Генерирует событие: DocumentUpdatedEvent (через RabbitMQ)
	UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// *
	// Отправка документа на согласование.
	// Запрос: document_id, recipient_id, message
	// Ответ: document
	// Генерирует событие: DocumentSentEvent (через RabbitMQ)
	SendDocument(ctx context.Context, in *SendDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// *
	// Одобрение документа.
	// Запрос: document_id, approved_by, comments
	// Ответ: document
	// Генерирует событие: DocumentApprovedEvent (через RabbitMQ)
	ApproveDocument(ctx context.Context, in *ApproveDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// *
	// Отклонение документа.
	// Запрос: document_id, rejected_by, reason
	// Ответ: document
	// Генерирует событие: DocumentRejectedEvent (через RabbitMQ)
	RejectDocument(ctx context.Context, in *RejectDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// *
	// Архивирование документа.
	// Запрос: document_id
	// Ответ: document
	// Генерирует событие: DocumentArchivedEvent (через RabbitMQ)
	ArchiveDocument(ctx context.Context, in *ArchiveDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// *
	// Список документов с пагинацией и фильтрами.
	// Запрос: organization_id, status, page, per_page
	// Ответ: список документов с информацией о пагинации
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	// *
	// Добавление записи в документ.
	// Запрос: document_id, key, value
	// Ответ: document_entry
	AddDocumentEntry(ctx context.Context, in *AddDocumentEntryRequest, opts ...grpc.CallOption) (*DocumentEntry, error)
	// *
	// Обновление записи документа.
	// Запрос: entry_id, key, value
	// Ответ: document_entry
	UpdateDocumentEntry(ctx context.Context, in *UpdateDocumentEntryRequest, opts ...grpc.CallOption) (*DocumentEntry, error)
	// *
	// Удаление записи документа.
	// Запрос: entry_id
	// Ответ: empty
	RemoveDocumentEntry(ctx context.Context, in *RemoveDocumentEntryRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// *
	// Получение истории документа.
	// Запрос: document_id, page, per_page
	// Ответ: версии документа
	GetDocumentHistory(ctx context.Context, in *GetDocumentHistoryRequest, opts ...grpc.CallOption) (*DocumentHistoryResponse, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_GetDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_CreateDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_UpdateDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) SendDocument(ctx context.Context, in *SendDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_SendDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ApproveDocument(ctx context.Context, in *ApproveDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_ApproveDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) RejectDocument(ctx context.Context, in *RejectDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_RejectDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ArchiveDocument(ctx context.Context, in *ArchiveDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_ArchiveDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListDocuments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) AddDocumentEntry(ctx context.Context, in *AddDocumentEntryRequest, opts ...grpc.CallOption) (*DocumentEntry, error) {
	out := new(DocumentEntry)
	err := c.cc.Invoke(ctx, DocumentService_AddDocumentEntry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UpdateDocumentEntry(ctx context.Context, in *UpdateDocumentEntryRequest, opts ...grpc.CallOption) (*DocumentEntry, error) {
	out := new(DocumentEntry)
	err := c.cc.Invoke(ctx, DocumentService_UpdateDocumentEntry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) RemoveDocumentEntry(ctx context.Context, in *RemoveDocumentEntryRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, DocumentService_RemoveDocumentEntry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetDocumentHistory(ctx context.Context, in *GetDocumentHistoryRequest, opts ...grpc.CallOption) (*DocumentHistoryResponse, error) {
	out := new(DocumentHistoryResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetDocumentHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility
type DocumentServiceServer interface {
	// *
	// Получение документа по ID.
	// Запрос: document_id
	// Ответ: документ со всеми записями
	GetDocument(context.Context, *GetDocumentRequest) (*Document, error)
	// *
	// Создание нового документа.
	// Запрос: organization_id, title, content, created_by
	// Ответ: document
	// Генерирует событие: DocumentCreatedEvent (через RabbitMQ)
	CreateDocument(context.Context, *CreateDocumentRequest) (*Document, error)
	// *
	// Обновление документа.
	// Запрос: id, title, content
	// Ответ: document
	// Генерирует событие: DocumentUpdatedEvent (через RabbitMQ)
	UpdateDocument(context.Context, *UpdateDocumentRequest) (*Document, error)
	// *
	// Отправка документа на согласование.
	// Запрос: document_id, recipient_id, message
	// Ответ: document
	// Генерирует событие: DocumentSentEvent (через RabbitMQ)
	SendDocument(context.Context, *SendDocumentRequest) (*Document, error)
	// *
	// Одобрение документа.
	// Запрос: document_id, approved_by, comments
	// Ответ: document
	// Генерирует событие: DocumentApprovedEvent (через RabbitMQ)
	ApproveDocument(context.Context, *ApproveDocumentRequest) (*Document, error)
	// *
	// Отклонение документа.
	// Запрос: document_id, rejected_by, reason
	// Ответ: document
	// Генерирует событие: DocumentRejectedEvent (через RabbitMQ)
	RejectDocument(context.Context, *RejectDocumentRequest) (*Document, error)
	// *
	// Архивирование документа.
	// Запрос: document_id
	// Ответ: document
	// Генерирует событие: DocumentArchivedEvent (через RabbitMQ)
	ArchiveDocument(context.Context, *ArchiveDocumentRequest) (*Document, error)
	// *
	// Список документов с пагинацией и фильтрами.
	// Запрос: organization_id, status, page, per_page
	// Ответ: список документов с информацией о пагинации
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	// *
	// Добавление записи в документ.
	// Запрос: document_id, key, value
	// Ответ: document_entry
	AddDocumentEntry(context.Context, *AddDocumentEntryRequest) (*DocumentEntry, error)
	// *
	// Обновление записи документа.
	// Запрос: entry_id, key, value
	// Ответ: document_entry
	UpdateDocumentEntry(context.Context, *UpdateDocumentEntryRequest) (*DocumentEntry, error)
	// *
	// Удаление записи документа.
	// Запрос: entry_id
	// Ответ: empty
	RemoveDocumentEntry(context.Context, *RemoveDocumentEntryRequest) (*common.Empty, error)
	// *
	// Получение истории документа.
	// Запрос: document_id, page, per_page
	// Ответ: версии документа
	GetDocumentHistory(context.Context, *GetDocumentHistoryRequest) (*DocumentHistoryResponse, error)
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentServiceServer struct {
}

func (UnimplementedDocumentServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDocumentServiceServer) CreateDocument(context.Context, *CreateDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedDocumentServiceServer) UpdateDocument(context.Context, *UpdateDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocument not implemented")
}
func (UnimplementedDocumentServiceServer) SendDocument(context.Context, *SendDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDocument not implemented")
}
func (UnimplementedDocumentServiceServer) ApproveDocument(context.Context, *ApproveDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveDocument not implemented")
}
func (UnimplementedDocumentServiceServer) RejectDocument(context.Context, *RejectDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectDocument not implemented")
}
func (UnimplementedDocumentServiceServer) ArchiveDocument(context.Context, *ArchiveDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveDocument not implemented")
}
func (UnimplementedDocumentServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedDocumentServiceServer) AddDocumentEntry(context.Context, *AddDocumentEntryRequest) (*DocumentEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDocumentEntry not implemented")
}
func (UnimplementedDocumentServiceServer) UpdateDocumentEntry(context.Context, *UpdateDocumentEntryRequest) (*DocumentEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocumentEntry not implemented")
}
func (UnimplementedDocumentServiceServer) RemoveDocumentEntry(context.Context, *RemoveDocumentEntryRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDocumentEntry not implemented")
}
func (UnimplementedDocumentServiceServer) GetDocumentHistory(context.Context, *GetDocumentHistoryRequest) (*DocumentHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentHistory not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_CreateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UpdateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UpdateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UpdateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UpdateDocument(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_SendDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).SendDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_SendDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).SendDocument(ctx, req.(*SendDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ApproveDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ApproveDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ApproveDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ApproveDocument(ctx, req.(*ApproveDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_RejectDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).RejectDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_RejectDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).RejectDocument(ctx, req.(*RejectDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ArchiveDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ArchiveDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ArchiveDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ArchiveDocument(ctx, req.(*ArchiveDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_AddDocumentEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDocumentEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).AddDocumentEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_AddDocumentEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).AddDocumentEntry(ctx, req.(*AddDocumentEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UpdateDocumentEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UpdateDocumentEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UpdateDocumentEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UpdateDocumentEntry(ctx, req.(*UpdateDocumentEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_RemoveDocumentEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDocumentEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).RemoveDocumentEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_RemoveDocumentEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).RemoveDocumentEntry(ctx, req.(*RemoveDocumentEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetDocumentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetDocumentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetDocumentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetDocumentHistory(ctx, req.(*GetDocumentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.document.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocument",
			Handler:    _DocumentService_GetDocument_Handler,
		},
		{
			MethodName: "CreateDocument",
			Handler:    _DocumentService_CreateDocument_Handler,
		},
		{
			MethodName: "UpdateDocument",
			Handler:    _DocumentService_UpdateDocument_Handler,
		},
		{
			MethodName: "SendDocument",
			Handler:    _DocumentService_SendDocument_Handler,
		},
		{
			MethodName: "ApproveDocument",
			Handler:    _DocumentService_ApproveDocument_Handler,
		},
		{
			MethodName: "RejectDocument",
			Handler:    _DocumentService_RejectDocument_Handler,
		},
		{
			MethodName: "ArchiveDocument",
			Handler:    _DocumentService_ArchiveDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _DocumentService_ListDocuments_Handler,
		},
		{
			MethodName: "AddDocumentEntry",
			Handler:    _DocumentService_AddDocumentEntry_Handler,
		},
		{
			MethodName: "UpdateDocumentEntry",
			Handler:    _DocumentService_UpdateDocumentEntry_Handler,
		},
		{
			MethodName: "RemoveDocumentEntry",
			Handler:    _DocumentService_RemoveDocumentEntry_Handler,
		},
		{
			MethodName: "GetDocumentHistory",
			Handler:    _DocumentService_GetDocumentHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "legacy/document_service.proto",
}
