// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dictionaries/bank_account.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BankAccount представляет банковский счет юридического лица.
// Содержит полную информацию о счете, открытом в кредитном учреждении.
//
// Банковские счета используются для:
//   - Указания реквизитов для поступления платежей в счетах-фактурах
//   - Хранения информации о счетах различных контрагентов
//   - Выполнения платежей и переводов
//   - Финансового учета и отчетности
//
// Каждый счет связан с конкретным банком и валютой,
// и может быть отмечен как активный или неиспользуемый.
type BankAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID - Уникальный идентификатор банковского счета в системе ТУНДУК.
	// Используется для ссылки на счет из других таблиц и документов.
	// Формат: UUID v4 (например, "550e8400-e29b-41d4-a716-446655440000")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// AccountName - Название/описание банковского счета.
	// Условное название для идентификации счета внутри организации.
	// Может отличаться от номера счета и служить для удобства пользователя.
	// Примеры:
	//   - "Основной расчетный счет"
	//   - "Счет для зарплаты сотрудников"
	//   - "Счет для поступления от покупателей"
	//   - "Валютный счет в USD"
	AccountName string `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	// BankAccount - Номер банковского счета.
	// Полный номер счета, открытого в банке.
	// Уникально идентифицирует счет в банке.
	// Используется для отправки платежей и финансовых операций.
	// Формат: обычно 20-24 цифры (в зависимости от страны и банка)
	// Примеры: "0012000012345678901234", "KG0123 KGBK 0000 0001"
	BankAccount string `protobuf:"bytes,3,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	// ContractorTIN - ИНН (Персональный идентификационный номер) контрагента.
	// Идентификатор организации/физического лица, владельца этого счета.
	// Используется для связи счета с его владельцем.
	// Формат: 14 цифр (например, "12345678901234")
	// Если счет принадлежит текущей организации, это может быть ее ИНН.
	// Если счет партнера/контрагента, это его ИНН.
	ContractorTin string `protobuf:"bytes,4,opt,name=contractor_tin,json=contractorTin,proto3" json:"contractor_tin,omitempty"`
	// IsActive - Флаг активности банковского счета.
	// true: счет активен и используется для операций
	// false: счет закрыт или временно не используется
	// Используется для фильтрации доступных счетов при создании документов.
	IsActive bool `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Currency - Валюта счета (KGS, USD, EUR и т.д.).
	// Определяет, в какой валюте открыт счет и проводятся операции.
	// Связан со справочником валют.
	Currency *ReferenceItem `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	// Bank - Информация о банке, в котором открыт счет.
	// Содержит наименование банка, БИК и адрес.
	// Обязательное поле для корректной идентификации банковского счета.
	Bank *Bank `protobuf:"bytes,7,opt,name=bank,proto3" json:"bank,omitempty"`
	// IsResident - Флаг резидентства владельца счета.
	// true: владелец счета является резидентом Кыргызской Республики
	// false: владелец счета является нерезидентом (иностранное лицо)
	// Влияет на применимые налоговые ставки и процедуры.
	IsResident bool `protobuf:"varint,8,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
}

func (x *BankAccount) Reset() {
	*x = BankAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionaries_bank_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccount) ProtoMessage() {}

func (x *BankAccount) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_bank_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccount.ProtoReflect.Descriptor instead.
func (*BankAccount) Descriptor() ([]byte, []int) {
	return file_dictionaries_bank_account_proto_rawDescGZIP(), []int{0}
}

func (x *BankAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BankAccount) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BankAccount) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

func (x *BankAccount) GetContractorTin() string {
	if x != nil {
		return x.ContractorTin
	}
	return ""
}

func (x *BankAccount) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *BankAccount) GetCurrency() *ReferenceItem {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *BankAccount) GetBank() *Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *BankAccount) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

var File_dictionaries_bank_account_proto protoreflect.FileDescriptor

var file_dictionaries_bank_account_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x62,
	0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x1a,
	0x17, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x62, 0x61,
	0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x02, 0x0a, 0x0b,
	0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x74, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x26,
	0x0a, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x6e, 0x6b,
	0x52, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52,
	0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x73, 0x67, 0x61, 0x69, 0x6e, 0x65, 0x77, 0x2f,
	0x6b, 0x6b, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x6d, 0x6b, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dictionaries_bank_account_proto_rawDescOnce sync.Once
	file_dictionaries_bank_account_proto_rawDescData = file_dictionaries_bank_account_proto_rawDesc
)

func file_dictionaries_bank_account_proto_rawDescGZIP() []byte {
	file_dictionaries_bank_account_proto_rawDescOnce.Do(func() {
		file_dictionaries_bank_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionaries_bank_account_proto_rawDescData)
	})
	return file_dictionaries_bank_account_proto_rawDescData
}

var file_dictionaries_bank_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_bank_account_proto_goTypes = []interface{}{
	(*BankAccount)(nil),   // 0: dictionaries.BankAccount
	(*ReferenceItem)(nil), // 1: dictionaries.ReferenceItem
	(*Bank)(nil),          // 2: dictionaries.Bank
}
var file_dictionaries_bank_account_proto_depIdxs = []int32{
	1, // 0: dictionaries.BankAccount.currency:type_name -> dictionaries.ReferenceItem
	2, // 1: dictionaries.BankAccount.bank:type_name -> dictionaries.Bank
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dictionaries_bank_account_proto_init() }
func file_dictionaries_bank_account_proto_init() {
	if File_dictionaries_bank_account_proto != nil {
		return
	}
	file_dictionaries_bank_proto_init()
	file_dictionaries_reference_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dictionaries_bank_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionaries_bank_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_bank_account_proto_goTypes,
		DependencyIndexes: file_dictionaries_bank_account_proto_depIdxs,
		MessageInfos:      file_dictionaries_bank_account_proto_msgTypes,
	}.Build()
	File_dictionaries_bank_account_proto = out.File
	file_dictionaries_bank_account_proto_rawDesc = nil
	file_dictionaries_bank_account_proto_goTypes = nil
	file_dictionaries_bank_account_proto_depIdxs = nil
}
