// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dictionaries/bank.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bank представляет информацию о банке/кредитном учреждении.
// Используется для получения информации о банке, в котором открыт счет.
//
// Информация о банке требуется при:
//   - Указании банковского счета в счете-фактуре
//   - Регистрации банковских счетов в системе
//   - Выполнении платежей
//   - Учете денежных потоков
//
// Содержит основные идентификационные данные банка, необходимые
// для валидации банковских счетов и проведения платежей.
type Bank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID - Уникальный идентификатор банка в системе ТУНДУК.
	// Используется для внутренней идентификации банка.
	// Пример: 1, 2, 3 и т.д.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name - Полное наименование банка на русском языке.
	// Официальное название кредитного учреждения.
	// Примеры:
	//   - "Азиатский банк"
	//   - "Кыргызский государственный банк"
	//   - "Универсал Банк"
	//   - "Берёзка Бизнес Банк"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// BIK - Банковский идентификационный код.
	// Уникальный код банка в системе платежей Кыргызской Республики.
	// Присваивается Национальным банком Кыргызской Республики.
	// Используется для маршрутизации платежей и идентификации банка.
	// Формат: обычно 5-6 цифр (например, "110014" для НБКР)
	Bik string `protobuf:"bytes,3,opt,name=bik,proto3" json:"bik,omitempty"`
	// AddressText - Адрес главного офиса банка.
	// Полный почтовый адрес расположения банка или его основного офиса.
	// Используется для справочных целей и контактной информации.
	// Примеры:
	//   - "г. Бишкек, ул. Чуй, 123"
	//   - "720040, Кыргызская Республика, г. Бишкек, ул. Pravdy 96"
	AddressText string `protobuf:"bytes,4,opt,name=address_text,json=addressText,proto3" json:"address_text,omitempty"`
}

func (x *Bank) Reset() {
	*x = Bank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionaries_bank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_bank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_dictionaries_bank_proto_rawDescGZIP(), []int{0}
}

func (x *Bank) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetBik() string {
	if x != nil {
		return x.Bik
	}
	return ""
}

func (x *Bank) GetAddressText() string {
	if x != nil {
		return x.AddressText
	}
	return ""
}

var File_dictionaries_bank_proto protoreflect.FileDescriptor

var file_dictionaries_bank_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x62,
	0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x04, 0x42, 0x61, 0x6e, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x62, 0x69, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x73, 0x67, 0x61, 0x69, 0x6e, 0x65, 0x77,
	0x2f, 0x6b, 0x6b, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x6d, 0x6b, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dictionaries_bank_proto_rawDescOnce sync.Once
	file_dictionaries_bank_proto_rawDescData = file_dictionaries_bank_proto_rawDesc
)

func file_dictionaries_bank_proto_rawDescGZIP() []byte {
	file_dictionaries_bank_proto_rawDescOnce.Do(func() {
		file_dictionaries_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionaries_bank_proto_rawDescData)
	})
	return file_dictionaries_bank_proto_rawDescData
}

var file_dictionaries_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_bank_proto_goTypes = []interface{}{
	(*Bank)(nil), // 0: dictionaries.Bank
}
var file_dictionaries_bank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_bank_proto_init() }
func file_dictionaries_bank_proto_init() {
	if File_dictionaries_bank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dictionaries_bank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionaries_bank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_bank_proto_goTypes,
		DependencyIndexes: file_dictionaries_bank_proto_depIdxs,
		MessageInfos:      file_dictionaries_bank_proto_msgTypes,
	}.Build()
	File_dictionaries_bank_proto = out.File
	file_dictionaries_bank_proto_rawDesc = nil
	file_dictionaries_bank_proto_goTypes = nil
	file_dictionaries_bank_proto_depIdxs = nil
}
