// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dictionaries/catalog.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Catalog представляет справочник товаров/услуг организации.
// Это внутренний справочник каждой организации, содержащий перечень
// товаров и услуг, которые она производит, продает или покупает.
//
// Использование каталога:
//   - Стандартизация описания товаров/услуг при создании счетов
//   - Быстрое заполнение счетов выбором из справочника
//   - Ведение истории товаров, которые продавались/покупались
//   - Управление классификацией и кодировкой товаров
//
// Каталог облегчает работу с документами и обеспечивает единообразие
// в описании товаров/услуг в различных счетах и договорах.
type Catalog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID - Уникальный идентификатор записи в справочнике.
	// Используется для ссылки на этот товар/услугу из счетов и других документов.
	// Формат: UUID v4 (например, "550e8400-e29b-41d4-a716-446655440000")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name - Полное наименование товара или оказываемой услуги.
	// Описание товара, как оно должно появляться в счетах-фактурах.
	// Должно быть четким, полным и недвусмысленным.
	// Примеры:
	//   - "Портативный компьютер ASUS VivoBook 15 (процессор Intel i7)"
	//   - "Услуга дизайна веб-сайта (от 40 до 80 часов работы)"
	//   - "Услуга консультирования по налоговому праву (1 час)"
	//   - "Кабель сетевой UTP категория 6, метр"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Number - Внутренний номер товара в справочнике организации.
	// Уникальный идентификатор товара в системе организации.
	// Может использоваться для быстрого поиска и идентификации.
	// Формат зависит от внутренней политики организации.
	// Примеры: "T001", "SKU-12345", "GOOD-2024-001"
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	// TNVEDCode - Код товара по ТНВЭД (Таможенная номенклатура внешнеэкономической деятельности).
	// Используется для таможенной классификации товара при импорте/экспорте.
	// Определяет применяемые таможенные пошлины, налоги и льготы.
	// Формат: 10 цифр (например, "8471.30.90")
	// Заполняется в основном для товаров, которые ввозятся/вывозятся.
	// Для услуг и отечественных товаров может быть пусто.
	TnvedCode string `protobuf:"bytes,4,opt,name=tnved_code,json=tnvedCode,proto3" json:"tnved_code,omitempty"`
	// GKEDCode - Код ГКЭД (Государственный классификатор видов экономической деятельности).
	// Используется для классификации товара/услуги по виду экономической деятельности.
	// Определяет отраслевую принадлежность и применяемые налоговые режимы.
	// Может быть пусто для некоторых товаров.
	GkedCode string `protobuf:"bytes,5,opt,name=gked_code,json=gkedCode,proto3" json:"gked_code,omitempty"`
	// UnitClassification - Единица измерения товара/услуги.
	// Определяет, в каких единицах измеряется количество товара.
	// Примеры: "PCS" (штук), "KG" (килограмм), "M" (метр), "HOUR" (часов)
	// Обязательное поле, используется при создании строк счета.
	UnitClassification *ReferenceItem `protobuf:"bytes,6,opt,name=unit_classification,json=unitClassification,proto3" json:"unit_classification,omitempty"`
	// CatalogType - Тип элемента справочника (товар или услуга).
	// Различение между материальными товарами и нематериальными услугами.
	// Примеры кодов: "GOODS" (товар), "SERVICE" (услуга)
	// Влияет на применимость налогов и способ отражения в учете.
	CatalogType *ReferenceItem `protobuf:"bytes,7,opt,name=catalog_type,json=catalogType,proto3" json:"catalog_type,omitempty"`
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionaries_catalog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_catalog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_dictionaries_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Catalog) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Catalog) GetTnvedCode() string {
	if x != nil {
		return x.TnvedCode
	}
	return ""
}

func (x *Catalog) GetGkedCode() string {
	if x != nil {
		return x.GkedCode
	}
	return ""
}

func (x *Catalog) GetUnitClassification() *ReferenceItem {
	if x != nil {
		return x.UnitClassification
	}
	return nil
}

func (x *Catalog) GetCatalogType() *ReferenceItem {
	if x != nil {
		return x.CatalogType
	}
	return nil
}

var File_dictionaries_catalog_proto protoreflect.FileDescriptor

var file_dictionaries_catalog_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x63,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x21, 0x64, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x02,
	0x0a, 0x07, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6e, 0x76, 0x65, 0x64, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6e, 0x76, 0x65, 0x64,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x6b, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6b, 0x65, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x4c, 0x0a, 0x13, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x12, 0x75, 0x6e, 0x69,
	0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3e, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75,
	0x73, 0x67, 0x61, 0x69, 0x6e, 0x65, 0x77, 0x2f, 0x6b, 0x6b, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2d, 0x6d, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x69,
	0x62, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dictionaries_catalog_proto_rawDescOnce sync.Once
	file_dictionaries_catalog_proto_rawDescData = file_dictionaries_catalog_proto_rawDesc
)

func file_dictionaries_catalog_proto_rawDescGZIP() []byte {
	file_dictionaries_catalog_proto_rawDescOnce.Do(func() {
		file_dictionaries_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionaries_catalog_proto_rawDescData)
	})
	return file_dictionaries_catalog_proto_rawDescData
}

var file_dictionaries_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_catalog_proto_goTypes = []interface{}{
	(*Catalog)(nil),       // 0: dictionaries.Catalog
	(*ReferenceItem)(nil), // 1: dictionaries.ReferenceItem
}
var file_dictionaries_catalog_proto_depIdxs = []int32{
	1, // 0: dictionaries.Catalog.unit_classification:type_name -> dictionaries.ReferenceItem
	1, // 1: dictionaries.Catalog.catalog_type:type_name -> dictionaries.ReferenceItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dictionaries_catalog_proto_init() }
func file_dictionaries_catalog_proto_init() {
	if File_dictionaries_catalog_proto != nil {
		return
	}
	file_dictionaries_reference_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dictionaries_catalog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Catalog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionaries_catalog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_catalog_proto_goTypes,
		DependencyIndexes: file_dictionaries_catalog_proto_depIdxs,
		MessageInfos:      file_dictionaries_catalog_proto_msgTypes,
	}.Build()
	File_dictionaries_catalog_proto = out.File
	file_dictionaries_catalog_proto_rawDesc = nil
	file_dictionaries_catalog_proto_goTypes = nil
	file_dictionaries_catalog_proto_depIdxs = nil
}
