// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dictionaries/country.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Country представляет страну с кодом и названием.
//
// Используется для указания страны происхождения товаров,
// страны регистрации контрагента или странах доставки.
// Коды стран соответствуют международному стандарту ISO 3166-1 alpha-3
// или другим классификаторам, используемым в Кыргызской Республике.
//
// Примеры:
//   - код="KGZ", название="Кыргызская Республика"
//   - код="RUS", название="Россия"
//   - код="KAZ", название="Казахстан"
//   - код="UZB", название="Узбекистан"
//   - код="CHN", название="Китайская Народная Республика"
type Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Code - Код страны по международному классификатору.
	// Обычно используется 3-символьный код ISO 3166-1 alpha-3,
	// но может быть использован другой формат в зависимости от
	// требований системы ТУНДУК.
	// Примеры: "KGZ", "RUS", "KAZ", "UZB", "CHN"
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Name - Полное наименование страны на русском языке.
	// Используется для отображения пользователю и в документах.
	// Примеры: "Кыргызская Республика", "Россия", "Казахстан"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Country) Reset() {
	*x = Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionaries_country_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_country_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_dictionaries_country_proto_rawDescGZIP(), []int{0}
}

func (x *Country) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dictionaries_country_proto protoreflect.FileDescriptor

var file_dictionaries_country_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x07, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x3d, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x73, 0x67,
	0x61, 0x69, 0x6e, 0x65, 0x77, 0x2f, 0x6b, 0x6b, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x2d, 0x6d, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x69, 0x62, 0x2f,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dictionaries_country_proto_rawDescOnce sync.Once
	file_dictionaries_country_proto_rawDescData = file_dictionaries_country_proto_rawDesc
)

func file_dictionaries_country_proto_rawDescGZIP() []byte {
	file_dictionaries_country_proto_rawDescOnce.Do(func() {
		file_dictionaries_country_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionaries_country_proto_rawDescData)
	})
	return file_dictionaries_country_proto_rawDescData
}

var file_dictionaries_country_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_country_proto_goTypes = []interface{}{
	(*Country)(nil), // 0: dictionaries.Country
}
var file_dictionaries_country_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_country_proto_init() }
func file_dictionaries_country_proto_init() {
	if File_dictionaries_country_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dictionaries_country_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionaries_country_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_country_proto_goTypes,
		DependencyIndexes: file_dictionaries_country_proto_depIdxs,
		MessageInfos:      file_dictionaries_country_proto_msgTypes,
	}.Build()
	File_dictionaries_country_proto = out.File
	file_dictionaries_country_proto_rawDesc = nil
	file_dictionaries_country_proto_goTypes = nil
	file_dictionaries_country_proto_depIdxs = nil
}
