// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dictionaries/foreign_company.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForeignCompany представляет иностранную компанию или иностранного контрагента.
// Используется для хранения информации об иностранных партнерах,
// с которыми организация осуществляет внешнеэкономическую деятельность.
//
// Отличие от обычного Party (юридического лица):
//   - Party используется для резидентов Кыргызской Республики с ИНН
//   - ForeignCompany используется для нерезидентов (иностранных компаний)
//
// Использование:
//   - Экспорт товаров иностранным покупателям
//   - Импорт товаров от иностранных поставщиков
//   - Оказание услуг иностранными компаниями
//   - Управление контрагентами из-за границы
//
// Содержит основные реквизиты иностранной компании, достаточные
// для идентификации и проведения трансграничных операций.
type ForeignCompany struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID - Уникальный идентификатор иностранной компании в системе ТУНДУК.
	// Используется для ссылки на компанию из счетов и других документов.
	// Пример: 1, 2, 3 и т.д.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// PIN - Идентификационный номер иностранной компании.
	// В разных странах это может быть:
	//   - Tax ID / TIN (Tax Identification Number) - Налоговый номер
	//   - VAT Number - Номер по НДС (для стран ЕС)
	//   - Registration Number - Номер регистрации
	//   - Business Number - Бизнес номер
	//   - UN/DUNS Number - Международный номер
	//
	// Используется для идентификации компании в налоговой системе страны происхождения.
	// Может быть пусто, если компания не имеет налогового номера в своей стране.
	// Примеры: "DE123456789", "FR12345678901", "IT12345678901"
	Pin string `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	// FullName - Полное наименование иностранной компании на языке оригинала.
	// Официальное зарегистрированное название компании.
	// Обычно указывается на английском языке или языке страны происхождения.
	// Примеры:
	//   - "Apple Inc."
	//   - "Microsoft Corporation"
	//   - "Samsung Electronics Co., Ltd."
	//   - "Siemens AG"
	//
	// Если название очень длинное, может быть сокращено в пределах разумного.
	FullName string `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
}

func (x *ForeignCompany) Reset() {
	*x = ForeignCompany{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionaries_foreign_company_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForeignCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignCompany) ProtoMessage() {}

func (x *ForeignCompany) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_foreign_company_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignCompany.ProtoReflect.Descriptor instead.
func (*ForeignCompany) Descriptor() ([]byte, []int) {
	return file_dictionaries_foreign_company_proto_rawDescGZIP(), []int{0}
}

func (x *ForeignCompany) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForeignCompany) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *ForeignCompany) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_dictionaries_foreign_company_proto protoreflect.FileDescriptor

var file_dictionaries_foreign_company_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x66,
	0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69,
	0x65, 0x73, 0x22, 0x4f, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x75, 0x73, 0x67, 0x61, 0x69, 0x6e, 0x65, 0x77, 0x2f, 0x6b, 0x6b, 0x6d, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x6d, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dictionaries_foreign_company_proto_rawDescOnce sync.Once
	file_dictionaries_foreign_company_proto_rawDescData = file_dictionaries_foreign_company_proto_rawDesc
)

func file_dictionaries_foreign_company_proto_rawDescGZIP() []byte {
	file_dictionaries_foreign_company_proto_rawDescOnce.Do(func() {
		file_dictionaries_foreign_company_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionaries_foreign_company_proto_rawDescData)
	})
	return file_dictionaries_foreign_company_proto_rawDescData
}

var file_dictionaries_foreign_company_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_foreign_company_proto_goTypes = []interface{}{
	(*ForeignCompany)(nil), // 0: dictionaries.ForeignCompany
}
var file_dictionaries_foreign_company_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_foreign_company_proto_init() }
func file_dictionaries_foreign_company_proto_init() {
	if File_dictionaries_foreign_company_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dictionaries_foreign_company_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForeignCompany); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionaries_foreign_company_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_foreign_company_proto_goTypes,
		DependencyIndexes: file_dictionaries_foreign_company_proto_depIdxs,
		MessageInfos:      file_dictionaries_foreign_company_proto_msgTypes,
	}.Build()
	File_dictionaries_foreign_company_proto = out.File
	file_dictionaries_foreign_company_proto_rawDesc = nil
	file_dictionaries_foreign_company_proto_goTypes = nil
	file_dictionaries_foreign_company_proto_depIdxs = nil
}
