// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dictionaries/vat_tax_type.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VATTaxType представляет вид налога НДС (налог на добавленную стоимость)
// с информацией о ставке и названии налога.
//
// Используется для указания налоговой ставки в счетах-фактурах.
// В Кыргызстане могут применяться различные ставки НДС в зависимости
// от типа товаров, услуг и условий поставки.
//
// Примеры:
//   - Стандартная ставка: rate="12%", name="НДС 12%"
//   - Льготная ставка: rate="0%", name="НДС не применяется"
//   - Повышенная ставка: rate="15%", name="НДС 15%"
type VATTaxType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Rate - Налоговая ставка НДС в процентах.
	// Строковое представление позволяет точно сохранить значение
	// без потери точности при вычислениях с целыми числами.
	// Примеры: "12%", "0%", "10%", "15%"
	Rate string `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	// Name - Наименование налога.
	// Описание применяемой ставки НДС, используется для отображения
	// пользователю и документах.
	// Примеры: "НДС 12%", "НДС 0% (не применяется)", "НДС 15% (повышенная)"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VATTaxType) Reset() {
	*x = VATTaxType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionaries_vat_tax_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VATTaxType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VATTaxType) ProtoMessage() {}

func (x *VATTaxType) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_vat_tax_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VATTaxType.ProtoReflect.Descriptor instead.
func (*VATTaxType) Descriptor() ([]byte, []int) {
	return file_dictionaries_vat_tax_type_proto_rawDescGZIP(), []int{0}
}

func (x *VATTaxType) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *VATTaxType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dictionaries_vat_tax_type_proto protoreflect.FileDescriptor

var file_dictionaries_vat_tax_type_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x76,
	0x61, 0x74, 0x5f, 0x74, 0x61, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x22,
	0x34, 0x0a, 0x0a, 0x56, 0x41, 0x54, 0x54, 0x61, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x73, 0x67, 0x61, 0x69, 0x6e, 0x65, 0x77, 0x2f, 0x6b, 0x6b,
	0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x6d, 0x6b, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dictionaries_vat_tax_type_proto_rawDescOnce sync.Once
	file_dictionaries_vat_tax_type_proto_rawDescData = file_dictionaries_vat_tax_type_proto_rawDesc
)

func file_dictionaries_vat_tax_type_proto_rawDescGZIP() []byte {
	file_dictionaries_vat_tax_type_proto_rawDescOnce.Do(func() {
		file_dictionaries_vat_tax_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionaries_vat_tax_type_proto_rawDescData)
	})
	return file_dictionaries_vat_tax_type_proto_rawDescData
}

var file_dictionaries_vat_tax_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_vat_tax_type_proto_goTypes = []interface{}{
	(*VATTaxType)(nil), // 0: dictionaries.VATTaxType
}
var file_dictionaries_vat_tax_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_vat_tax_type_proto_init() }
func file_dictionaries_vat_tax_type_proto_init() {
	if File_dictionaries_vat_tax_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dictionaries_vat_tax_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VATTaxType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionaries_vat_tax_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_vat_tax_type_proto_goTypes,
		DependencyIndexes: file_dictionaries_vat_tax_type_proto_depIdxs,
		MessageInfos:      file_dictionaries_vat_tax_type_proto_msgTypes,
	}.Build()
	File_dictionaries_vat_tax_type_proto = out.File
	file_dictionaries_vat_tax_type_proto_rawDesc = nil
	file_dictionaries_vat_tax_type_proto_goTypes = nil
	file_dictionaries_vat_tax_type_proto_depIdxs = nil
}
