// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: entities/invoice_contract.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractData содержит данные контракта/договора для счета-фактуры.
// Используется для привязки счета к исходному договору поставки.
type ContractData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DeliveryContractNumber - Номер договора поставки/контракта.
	// Номер основного договора, на основе которого создается счет.
	DeliveryContractNumber string `protobuf:"bytes,1,opt,name=delivery_contract_number,json=deliveryContractNumber,proto3" json:"delivery_contract_number,omitempty"`
	// DeliveryContractDate - Дата договора поставки.
	// Дата подписания основного договора поставки.
	// Формат: ISO 8601 (YYYY-MM-DD)
	DeliveryContractDate *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=delivery_contract_date,json=deliveryContractDate,proto3" json:"delivery_contract_date,omitempty"`
	// OwnedCrmReceiptCode - Код документа в системе CRM поставщика.
	// Используется для связи с внешней CRM/ERP системой.
	OwnedCrmReceiptCode string `protobuf:"bytes,3,opt,name=owned_crm_receipt_code,json=ownedCrmReceiptCode,proto3" json:"owned_crm_receipt_code,omitempty"`
}

func (x *ContractData) Reset() {
	*x = ContractData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entities_invoice_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractData) ProtoMessage() {}

func (x *ContractData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_invoice_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractData.ProtoReflect.Descriptor instead.
func (*ContractData) Descriptor() ([]byte, []int) {
	return file_entities_invoice_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ContractData) GetDeliveryContractNumber() string {
	if x != nil {
		return x.DeliveryContractNumber
	}
	return ""
}

func (x *ContractData) GetDeliveryContractDate() *wrapperspb.StringValue {
	if x != nil {
		return x.DeliveryContractDate
	}
	return nil
}

func (x *ContractData) GetOwnedCrmReceiptCode() string {
	if x != nil {
		return x.OwnedCrmReceiptCode
	}
	return ""
}

var File_entities_invoice_contract_proto protoreflect.FileDescriptor

var file_entities_invoice_contract_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x0c,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x18,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x16, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x14, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x16, 0x6f, 0x77,
	0x6e, 0x65, 0x64, 0x5f, 0x63, 0x72, 0x6d, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6f, 0x77, 0x6e, 0x65,
	0x64, 0x43, 0x72, 0x6d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75,
	0x73, 0x67, 0x61, 0x69, 0x6e, 0x65, 0x77, 0x2f, 0x6b, 0x6b, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2d, 0x6d, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x69,
	0x62, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_entities_invoice_contract_proto_rawDescOnce sync.Once
	file_entities_invoice_contract_proto_rawDescData = file_entities_invoice_contract_proto_rawDesc
)

func file_entities_invoice_contract_proto_rawDescGZIP() []byte {
	file_entities_invoice_contract_proto_rawDescOnce.Do(func() {
		file_entities_invoice_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_entities_invoice_contract_proto_rawDescData)
	})
	return file_entities_invoice_contract_proto_rawDescData
}

var file_entities_invoice_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_invoice_contract_proto_goTypes = []interface{}{
	(*ContractData)(nil),           // 0: entities.ContractData
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
}
var file_entities_invoice_contract_proto_depIdxs = []int32{
	1, // 0: entities.ContractData.delivery_contract_date:type_name -> google.protobuf.StringValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entities_invoice_contract_proto_init() }
func file_entities_invoice_contract_proto_init() {
	if File_entities_invoice_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entities_invoice_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entities_invoice_contract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_invoice_contract_proto_goTypes,
		DependencyIndexes: file_entities_invoice_contract_proto_depIdxs,
		MessageInfos:      file_entities_invoice_contract_proto_msgTypes,
	}.Build()
	File_entities_invoice_contract_proto = out.File
	file_entities_invoice_contract_proto_rawDesc = nil
	file_entities_invoice_contract_proto_goTypes = nil
	file_entities_invoice_contract_proto_depIdxs = nil
}
