// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: legacy/auth_service.proto

package auth

import (
	context "context"
	common "github.com/rusgainew/kkm-project-mks/proto-lib/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthService_Register_FullMethodName       = "/api.auth.AuthService/Register"
	AuthService_Login_FullMethodName          = "/api.auth.AuthService/Login"
	AuthService_ValidateToken_FullMethodName  = "/api.auth.AuthService/ValidateToken"
	AuthService_GetUser_FullMethodName        = "/api.auth.AuthService/GetUser"
	AuthService_GetCurrentUser_FullMethodName = "/api.auth.AuthService/GetCurrentUser"
	AuthService_Logout_FullMethodName         = "/api.auth.AuthService/Logout"
	AuthService_RefreshToken_FullMethodName   = "/api.auth.AuthService/RefreshToken"
	AuthService_UpdateProfile_FullMethodName  = "/api.auth.AuthService/UpdateProfile"
	AuthService_ChangePassword_FullMethodName = "/api.auth.AuthService/ChangePassword"
	AuthService_ListUsers_FullMethodName      = "/api.auth.AuthService/ListUsers"
	AuthService_ForgotPassword_FullMethodName = "/api.auth.AuthService/ForgotPassword"
	AuthService_ResetPassword_FullMethodName  = "/api.auth.AuthService/ResetPassword"
	AuthService_AssignRole_FullMethodName     = "/api.auth.AuthService/AssignRole"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// *
	// Регистрация нового пользователя в системе.
	//
	// Валидация:
	// - email: формат RFC 5322, уникальность
	// - password: минимум 8 символов, uppercase, lowercase, digit, special char
	// - first_name, last_name: обязательные, 1-100 символов
	//
	// Ответ:
	// - user: информация о созданном пользователе (БЕЗ password_hash)
	// - token: JWT access_token + refresh_token
	// - timestamp: Unix миллисекунды момента регистрации
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидные данные
	// - ERROR_CODE_ALREADY_EXISTS (409): email уже зарегистрирован
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// *
	// Вход существующего пользователя в систему.
	//
	// Валидация:
	// - email: формат RFC 5322
	// - password: не пустой
	//
	// Ответ:
	// - user: информация о пользователе (БЕЗ password_hash)
	// - token: JWT access_token + refresh_token
	// - timestamp: Unix миллисекунды момента входа
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): неверные credentials
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден
	// - ERROR_CODE_FORBIDDEN (403): пользователь заблокирован (status="banned")
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// *
	// Валидация токена доступа и получение информации о пользователе.
	//
	// Используется:
	// - api-gateway: middleware для всех защищенных endpoints
	// - другими сервисами: проверка токена в gRPC metadata
	//
	// Валидация:
	// - JWT подпись (RS256)
	// - exp (expiration time)
	// - iat (issued at)
	// - sub (subject = user_id)
	//
	// Ответ:
	// - user: полная информация о пользователе (БЕЗ password_hash)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный/просроченный токен
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден (удален после выдачи токена)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*User, error)
	// *
	// Получение пользователя по ID.
	//
	// Используется:
	// - внутренними сервисами для получения информации о владельце ресурса
	// - admin панелью для просмотра профилей
	//
	// Валидация:
	// - user_id: формат UUID v4
	//
	// Ответ:
	// - user: информация о пользователе (БЕЗ password_hash)
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидный UUID
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// *
	// Получение текущего пользователя из токена.
	//
	// Convenience метод, эквивалентный ValidateToken, но с более удобным именем.
	// Используется для endpoint GET /api/v1/users/me
	//
	// Валидация:
	// - access_token: JWT signature, expiration
	//
	// Ответ:
	// - user: полная информация о текущем пользователе (БЕЗ password_hash)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный/просроченный токен
	GetCurrentUser(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*User, error)
	// *
	// Выход пользователя (инвалидация токена).
	//
	// Действия:
	// - добавление access_token в blacklist (Redis с TTL = оставшееся время жизни токена)
	// - опционально: инвалидация всех refresh_token пользователя
	//
	// Валидация:
	// - access_token: JWT signature, expiration
	//
	// Ответ:
	// - Empty (статус 200 означает успех)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный токен
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// *
	// Обновление токена доступа с помощью refresh token.
	//
	// Используется для "silent" обновления access_token без повторного логина.
	//
	// Валидация:
	// - refresh_token: JWT signature, expiration
	// - refresh_token не должен быть в blacklist
	//
	// Ответ:
	// - token: новая пара access_token + refresh_token
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный/просроченный refresh_token
	// - ERROR_CODE_FORBIDDEN (403): refresh_token в blacklist
	//
	// Примечание:
	// - старый refresh_token инвалидируется (добавляется в blacklist)
	// - возвращается новая пара токенов для реализации token rotation
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*Token, error)
	// *
	// Обновление профиля пользователя.
	//
	// Позволяет изменить: first_name, last_name
	// Для смены email/password используйте отдельные методы.
	//
	// Валидация:
	// - user_id: UUID v4, должен совпадать с токеном (или admin role)
	// - first_name, last_name: 1-100 символов
	//
	// Ответ:
	// - user: обновленная информация о пользователе
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидные данные
	// - ERROR_CODE_UNAUTHORIZED (401): токен отсутствует/невалиден
	// - ERROR_CODE_FORBIDDEN (403): попытка изменить чужой профиль (не admin)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*User, error)
	// *
	// Смена пароля пользователя.
	//
	// Требует знания текущего пароля для безопасности.
	//
	// Валидация:
	// - old_password: должен совпадать с текущим
	// - new_password: минимум 8 символов, uppercase, lowercase, digit, special char
	// - new_password != old_password
	//
	// Действия:
	// - обновление password_hash
	// - инвалидация всех существующих токенов пользователя (добавление в blacklist)
	//
	// Ответ:
	// - Empty (статус 200 означает успех)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): неверный old_password или токен
	// - ERROR_CODE_VALIDATION_FAILED (400): слабый new_password
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// *
	// Список всех пользователей с пагинацией.
	//
	// Требует роль: admin
	//
	// Валидация:
	// - page, size: page >= 0, 0 < size <= 100
	//
	// Ответ:
	// - users: список пользователей (БЕЗ password_hash)
	// - page_info: информация о пагинации
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): токен отсутствует/невалиден
	// - ERROR_CODE_FORBIDDEN (403): недостаточно прав (не admin)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// *
	// Запрос на восстановление пароля (забытый пароль).
	//
	// Действия:
	// - проверка существования пользователя по email
	// - генерация token для сброса пароля (valid 15 минут)
	// - отправка email с ссылкой для сброса (требует email сервис)
	//
	// Валидация:
	// - email: формат RFC 5322, должен существовать в системе
	//
	// Ответ:
	// - Empty (статус 200 означает успех)
	// - Email с инструкциями отправлен (или fake успех для защиты от enumeration)
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидный email
	//
	// Примечание:
	// - возвращается успех даже если email не найден (защита от перечисления)
	// - token отправляется по email (требует настройки SMTP)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// *
	// Сброс пароля с использованием token из email.
	//
	// Действия:
	// - валидация reset token
	// - проверка что новый пароль отличается от старого
	// - обновление пароля
	// - инвалидация всех существующих токенов пользователя
	//
	// Валидация:
	// - reset_token: должен быть корректным и не просроченным (15 минут)
	// - new_password: минимум 8 символов, uppercase, lowercase, digit, special char
	//
	// Ответ:
	// - token: новая пара access_token + refresh_token для автоматического входа
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидный token или пароль
	// - ERROR_CODE_UNAUTHENTICATED (401): просроченный reset token
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден (token был выдан несуществующему пользователю)
	//
	// Примечание:
	// - reset token может быть использован только один раз
	// - все существующие сессии пользователя завершаются
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// *
	// Назначение роли пользователю (только админ).
	//
	// Действия:
	// - извлечение актёра из access_token
	// - проверка, что актёр имеет роль admin
	// - назначение целевому пользователю роли "manager" или "user"
	//
	// Ограничения:
	// - роль "manager" не имеет права удалять записи из базы
	// - роль "admin" назначать через этот метод нельзя (защита от эскалации)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный токен
	// - ERROR_CODE_FORBIDDEN (403): недостаточно прав (не admin)
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидная роль или пользователь
	AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*User, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_ValidateToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetCurrentUser(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_GetCurrentUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_UpdateProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, AuthService_ChangePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, AuthService_ListUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, AuthService_ForgotPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_ResetPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, AuthService_AssignRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	// *
	// Регистрация нового пользователя в системе.
	//
	// Валидация:
	// - email: формат RFC 5322, уникальность
	// - password: минимум 8 символов, uppercase, lowercase, digit, special char
	// - first_name, last_name: обязательные, 1-100 символов
	//
	// Ответ:
	// - user: информация о созданном пользователе (БЕЗ password_hash)
	// - token: JWT access_token + refresh_token
	// - timestamp: Unix миллисекунды момента регистрации
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидные данные
	// - ERROR_CODE_ALREADY_EXISTS (409): email уже зарегистрирован
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	// *
	// Вход существующего пользователя в систему.
	//
	// Валидация:
	// - email: формат RFC 5322
	// - password: не пустой
	//
	// Ответ:
	// - user: информация о пользователе (БЕЗ password_hash)
	// - token: JWT access_token + refresh_token
	// - timestamp: Unix миллисекунды момента входа
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): неверные credentials
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден
	// - ERROR_CODE_FORBIDDEN (403): пользователь заблокирован (status="banned")
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	// *
	// Валидация токена доступа и получение информации о пользователе.
	//
	// Используется:
	// - api-gateway: middleware для всех защищенных endpoints
	// - другими сервисами: проверка токена в gRPC metadata
	//
	// Валидация:
	// - JWT подпись (RS256)
	// - exp (expiration time)
	// - iat (issued at)
	// - sub (subject = user_id)
	//
	// Ответ:
	// - user: полная информация о пользователе (БЕЗ password_hash)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный/просроченный токен
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден (удален после выдачи токена)
	ValidateToken(context.Context, *ValidateTokenRequest) (*User, error)
	// *
	// Получение пользователя по ID.
	//
	// Используется:
	// - внутренними сервисами для получения информации о владельце ресурса
	// - admin панелью для просмотра профилей
	//
	// Валидация:
	// - user_id: формат UUID v4
	//
	// Ответ:
	// - user: информация о пользователе (БЕЗ password_hash)
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидный UUID
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден
	GetUser(context.Context, *GetUserRequest) (*User, error)
	// *
	// Получение текущего пользователя из токена.
	//
	// Convenience метод, эквивалентный ValidateToken, но с более удобным именем.
	// Используется для endpoint GET /api/v1/users/me
	//
	// Валидация:
	// - access_token: JWT signature, expiration
	//
	// Ответ:
	// - user: полная информация о текущем пользователе (БЕЗ password_hash)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный/просроченный токен
	GetCurrentUser(context.Context, *ValidateTokenRequest) (*User, error)
	// *
	// Выход пользователя (инвалидация токена).
	//
	// Действия:
	// - добавление access_token в blacklist (Redis с TTL = оставшееся время жизни токена)
	// - опционально: инвалидация всех refresh_token пользователя
	//
	// Валидация:
	// - access_token: JWT signature, expiration
	//
	// Ответ:
	// - Empty (статус 200 означает успех)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный токен
	Logout(context.Context, *LogoutRequest) (*common.Empty, error)
	// *
	// Обновление токена доступа с помощью refresh token.
	//
	// Используется для "silent" обновления access_token без повторного логина.
	//
	// Валидация:
	// - refresh_token: JWT signature, expiration
	// - refresh_token не должен быть в blacklist
	//
	// Ответ:
	// - token: новая пара access_token + refresh_token
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный/просроченный refresh_token
	// - ERROR_CODE_FORBIDDEN (403): refresh_token в blacklist
	//
	// Примечание:
	// - старый refresh_token инвалидируется (добавляется в blacklist)
	// - возвращается новая пара токенов для реализации token rotation
	RefreshToken(context.Context, *RefreshTokenRequest) (*Token, error)
	// *
	// Обновление профиля пользователя.
	//
	// Позволяет изменить: first_name, last_name
	// Для смены email/password используйте отдельные методы.
	//
	// Валидация:
	// - user_id: UUID v4, должен совпадать с токеном (или admin role)
	// - first_name, last_name: 1-100 символов
	//
	// Ответ:
	// - user: обновленная информация о пользователе
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидные данные
	// - ERROR_CODE_UNAUTHORIZED (401): токен отсутствует/невалиден
	// - ERROR_CODE_FORBIDDEN (403): попытка изменить чужой профиль (не admin)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*User, error)
	// *
	// Смена пароля пользователя.
	//
	// Требует знания текущего пароля для безопасности.
	//
	// Валидация:
	// - old_password: должен совпадать с текущим
	// - new_password: минимум 8 символов, uppercase, lowercase, digit, special char
	// - new_password != old_password
	//
	// Действия:
	// - обновление password_hash
	// - инвалидация всех существующих токенов пользователя (добавление в blacklist)
	//
	// Ответ:
	// - Empty (статус 200 означает успех)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): неверный old_password или токен
	// - ERROR_CODE_VALIDATION_FAILED (400): слабый new_password
	ChangePassword(context.Context, *ChangePasswordRequest) (*common.Empty, error)
	// *
	// Список всех пользователей с пагинацией.
	//
	// Требует роль: admin
	//
	// Валидация:
	// - page, size: page >= 0, 0 < size <= 100
	//
	// Ответ:
	// - users: список пользователей (БЕЗ password_hash)
	// - page_info: информация о пагинации
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): токен отсутствует/невалиден
	// - ERROR_CODE_FORBIDDEN (403): недостаточно прав (не admin)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// *
	// Запрос на восстановление пароля (забытый пароль).
	//
	// Действия:
	// - проверка существования пользователя по email
	// - генерация token для сброса пароля (valid 15 минут)
	// - отправка email с ссылкой для сброса (требует email сервис)
	//
	// Валидация:
	// - email: формат RFC 5322, должен существовать в системе
	//
	// Ответ:
	// - Empty (статус 200 означает успех)
	// - Email с инструкциями отправлен (или fake успех для защиты от enumeration)
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидный email
	//
	// Примечание:
	// - возвращается успех даже если email не найден (защита от перечисления)
	// - token отправляется по email (требует настройки SMTP)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*common.Empty, error)
	// *
	// Сброс пароля с использованием token из email.
	//
	// Действия:
	// - валидация reset token
	// - проверка что новый пароль отличается от старого
	// - обновление пароля
	// - инвалидация всех существующих токенов пользователя
	//
	// Валидация:
	// - reset_token: должен быть корректным и не просроченным (15 минут)
	// - new_password: минимум 8 символов, uppercase, lowercase, digit, special char
	//
	// Ответ:
	// - token: новая пара access_token + refresh_token для автоматического входа
	//
	// Ошибки:
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидный token или пароль
	// - ERROR_CODE_UNAUTHENTICATED (401): просроченный reset token
	// - ERROR_CODE_NOT_FOUND (404): пользователь не найден (token был выдан несуществующему пользователю)
	//
	// Примечание:
	// - reset token может быть использован только один раз
	// - все существующие сессии пользователя завершаются
	ResetPassword(context.Context, *ResetPasswordRequest) (*AuthResponse, error)
	// *
	// Назначение роли пользователю (только админ).
	//
	// Действия:
	// - извлечение актёра из access_token
	// - проверка, что актёр имеет роль admin
	// - назначение целевому пользователю роли "manager" или "user"
	//
	// Ограничения:
	// - роль "manager" не имеет права удалять записи из базы
	// - роль "admin" назначать через этот метод нельзя (защита от эскалации)
	//
	// Ошибки:
	// - ERROR_CODE_UNAUTHORIZED (401): невалидный токен
	// - ERROR_CODE_FORBIDDEN (403): недостаточно прав (не admin)
	// - ERROR_CODE_VALIDATION_FAILED (400): невалидная роль или пользователь
	AssignRole(context.Context, *AssignRoleRequest) (*User, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthServiceServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAuthServiceServer) GetCurrentUser(context.Context, *ValidateTokenRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentUser not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedAuthServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAuthServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAuthServiceServer) ForgotPassword(context.Context, *ForgotPasswordRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (UnimplementedAuthServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAuthServiceServer) AssignRole(context.Context, *AssignRoleRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignRole not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetCurrentUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetCurrentUser(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ForgotPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_AssignRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AssignRole(ctx, req.(*AssignRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AuthService_ValidateToken_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthService_GetUser_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _AuthService_GetCurrentUser_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _AuthService_UpdateProfile_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AuthService_ChangePassword_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _AuthService_ListUsers_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AuthService_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AuthService_ResetPassword_Handler,
		},
		{
			MethodName: "AssignRole",
			Handler:    _AuthService_AssignRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "legacy/auth_service.proto",
}
